services:
  - type: web
    name: zino-quotex-signal-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
